<div class="card">
    <div class="card-body">
        <h5 class="card-title">SPARQL - Query</h5>
        <p class="card-text">
            Total items in dataset: <?= $this->escapeHtml($doc_count) ?>
            <div id="yasgui"></div>
            <script>
                var yasqe = YASQE(document.getElementById("yasgui"));
            </script>
        <form id="sparqlForm">
            <div class="row">
                <div class="col-md-6"><label for="queryKey">Select a key to use for this query</label><br /></div>
                <div class="col-md-4"> <label for="resultsFormat">Results format</label><br /></div>
                <div class="col-md-2">&nbsp;</div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">

                    <select class="custom-select custom-select-sm" id="queryKey">
                        <?php
                            foreach ($keys as $key) {
                                echo ("<option value='".$key['keyUUID']."'>".$key['keyName']." [".$key['keyUUID']."]</option>");
                            }
                        ?>
                    </select>
                </div>
                <div class="form-group col-md-4">

                    <select class="custom-select custom-select-sm" id="resultsFormat">
                        <option value="application/sparql-results+json">JSON</option>
                        <option value="application/sparql-results+xml">XML</option>
                        <option value="text/csv">Comma separated values</option>
                        <option value="text/tab-separated-values">Tab separated values</option>
                    </select>
                </div>
                <div class="col-md-2 align-baseline">
                    <button type="submit" class="btn btn-primary btn-sm align-baseline"><i class="fas fa-play"></i> Go</button>
                </div>
            </div>
        </form>
        </p>
        <div id="queryRunning" class="alert alert-primary" role="alert">
            Query running...
        </div>
        <div id="errorBox" class="alert alert-warning" role="alert">
            Error
        </div>
    <div id="yasr"></div>
    <script>
        var yasr = YASR(document.getElementById("yasr"),{
            outputPlugins: ["error", "boolean", "rawResponse", "table", "leaflet"],
            useGoogleCharts: false,
            persistency: false
        });
    </script>
    </div>
</div>

<script>
    $( document ).ready(function() {
        $("#errorBox").hide();
        $("#queryRunning").hide();
    });

    $('#sparqlForm').on('submit', function(e) {
        e.preventDefault();
        e.stopPropagation(); // only neccessary if something above is listening to the (default-)event too

        $("#errorBox").hide();
        $("#queryRunning").show();

        var query = yasqe.getValue();
        var data = {
            'query': query
        };
        var key = $("#queryKey").val();
        var resultsFormat = $( "#resultsFormat" ).val();
        var ajaxCall = $.ajax
        ({
            type: "GET",
            url: "<?= $api_home ?>" +  "/query/" + "<?= $dataset->uuid ?>" + "/sparql",
            dataType: 'text',
            headers: {
                Accept: resultsFormat
            },
            beforeSend: function (xhr) {
                xhr.setRequestHeader ("Authorization", "Basic " + btoa(key + ":" + key));
            },
            data: data,
            success: function (){
                //handled below
            }
        });

        ajaxCall.done(function(text) {
            $("#queryRunning").hide();
            $("#errorBox").hide();
            yasr.setResponse({
                response: text,
                contentType: resultsFormat
            });

            // Draw results with current plugin
            yasr.draw()
        });
        ajaxCall.fail(function(response) {
            $("#queryRunning").hide();
            var error;
            switch(response.status) {
                case 400:
                    error = "Error: Invalid SPARQL query";
                    break;
                case 401:
                    error = "Authentication error: The key provided does not have read access on this dataset. Check that access for this key has not been disabled";
                    break;
                case 404:
                    error = "Graph database not found. This dataset may not yet be enabled for SPARQL queries";
                    break;
                default:
                    error = "An error occurred. The graph database may be offline or this dataset may not yet be enabled for SPARQL queries";
            }
            $("#errorBox").html(error);
            $("#errorBox").show();
        });
        ajaxCall.always(function() {
            //this always runs when ajax complete regardless of the result
        });
    });

</script>


