<div class="card">
    <div class="card-body">
        <h5 class="card-title">Dataset SPARQL Interface</h5>
        <p class="card-text">
            Total items in dataset: <?= $this->escapeHtml($doc_count) ?>



        <?php if ($can_read && $user_has_key):  ?>

            <div id="yasgui"></div>
            <script>
                var yasqe = YASQE(document.getElementById("yasgui"));
            </script>

        <form>
            <div class="form-group">
                <label for="queryKey">Select a key to use for this query</label>
                <select class="custom-select custom-select-sm" id="queryKey">
                    <option selected>Open this select menu</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary"><i class="fas fa-play"></i> Go</button>
        </form>



        <?php endif; ?>
        </p>

    </div>
</div>


