<h1><?= $dataset->title ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <?php
            if ($can_read && !$user_has_key && $stream_exists){
                //Add subscribe button
                $actions['buttons'][] = [
                    'type' => 'primary',
                    'label' => 'Subscribe',
                    'icon' => 'bookmark',
                    'target' => 'stream',
                    'params' => [
                        'action' => 'subscribe',
                        'id' => $dataset->id
                    ]
                ];
            }
            ?>

            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->


                <?= $this->partial('mkdf/sparql/partial/query-interface', [
                    'stream_url'    => $stream_url,
                    'read_url'	=> $read_url,
                    'write_url'	=> $write_url,
                    'browse_url'	=> $browse_url,
                    'api_home'	=> $api_home,
                    'doc_count'     => $doc_count,
                    'dataset'       => $dataset,
                    'can_read'      => $can_read,
                    'user_has_key'  => $user_has_key
                ] ) ?>



        </div>
    </div>
</div>